Update input.yml

diff --git a/.github/workflows/input.yml b/.github/workflows/input.yml
--- a/.github/workflows/input.yml
+++ b/.github/workflows/input.yml
@@ -1,35 +1,45 @@
-# This is a basic workflow that is manually triggered
-
-name: Manual workflow
-
-# Controls when the action will run. Workflow runs when manually triggered using the UI
-# or API.
-
-
-
+name: Input Testing Workflow
 on:
   workflow_dispatch:
-    # Inputs the workflow accepts.
     inputs:
-      name:
-        # Friendly description to be shown in the UI instead of 'name'
-        description: 'Person to greet'
-        # Default value if no value is explicitly provided
-        default: 'World'
-        # Input has to be provided for the workflow to run
+      input1:
+        description: 'Input 1'
+        required: false
+        default: 'default-value-1'
+      input2:
+        description: 'Input 2'
         required: true
-        # The data type of the input
-        type: string
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "greet"
-  greet:
-    # The type of runner that the job will run on
+  test:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-    # Runs a single command using the runners shell
-    - name: Send greeting
-      run: echo "Hello ${{ inputs.name }}"
+      - name: Check Inputs
+        run: |
+          input1=${{ github.event.inputs.input1 }}
+          input2=${{ github.event.inputs.input2 }}
+
+          if [[ -z $input1 ]]; then
+            input1='default-value-1'
+          fi
+
+          if [[ $input2 == "world" ]]; then
+            echo "Input 2 is valid!"
+          else
+            echo "Invalid input for Input 2!"
+            exit 1
+          fi
+
+      - name: Display Output
+        run: |
+          input1=${{ github.event.inputs.input1 }}
+          input2=${{ github.event.inputs.input2 }}
+
+          if [[ $input1 == "default-value-1" && $input2 == "world" ]]; then
+            echo "Output: Greetings, world!"
+          elif [[ $input1 == "default-value-1" && $input2 == "sesame" ]]; then
+            echo "Output: The magic word is correct!"
+          else
+            echo "Output: Unknown input combination."
+          fi
